module: RxPullToRefresh

author: Kojiro Futamura
author_url: https://github.com/futamura
github_url: https://github.com/futamura/RxPullToRefresh
copyright: 'Copyright © 2018 Kojiro Futamura. All rights reserved.'

min_acl: public
clean: true
readme: "README.md"
output: "docs"
documentation: "USAGE.md"
skip_undocumented: true
hide_documentation_coverage: true
# theme: fullwidth
theme: "themes/fullwidth-ex"

source_directory: Sources
umbrella_header: "Sources/RxPullToRefresh.h"
xcodebuild_arguments:
  - -project
  - ../RxPullToRefresh.xcodeproj
  - -scheme
  - RxPullToRefresh
exclude:
  - Sources/DefaultRefreshView.swift
#  - Sources/Extensions.swift
  - Sources/Helpers.swift
custom_categories:
  - name: Classes
    children:
    - RxPullToRefresh
    - RxPullToRefreshView
  - name: Delegate
    children:
    - RxPullToRefreshDelegate
  - name: Extensions
    children:
    - Reactive
    - RxPullToRefreshProxy
    - RxPullToRefreshCompatible
  - name: Enumerations
    children:
    - RxPullToRefreshPosition
    - RxPullToRefreshState
    - RxPullToRefreshAnimationType
  - name: Guides
    children:
    - USAGE